### Ajouter un impact
POST http://localhost:3000/api/impacts
Content-Type: application/json

{
  "impact": "Identifier le potentiel des matériaux\nEtablir un inventaire des réemployables (briques, bois, revêtement ext.)\nEffectuer un tri sélectif à la source (organisation, localisation, suivi)",
  "importance": 2,
  "metier": 1,
  "composante": 1,
  "thematique": 2
}

### Inscription d'un utilisateur
POST http://localhost:3000/api/auth/inscription
Content-Type: application/json

{
  "nom_utilisateur": "TestUser",
  "email": "testuser@example.com",
  "mot_de_passe": "123456"
}

### Connexion d'un utilisateur
POST http://localhost:3000/api/auth/connexion
Content-Type: application/json

{
  "email": "testuser@example.com",
  "mot_de_passe": "123456"
}

### Création d'une checklist
POST http://localhost:3000/api/checklists
Content-Type: application/json

{
  "utilisateur": 1,
  "nom_checklist": "hey",
  "impacts": [1, 2, 3, 4, 5]
}

### Récupérer les checklists d'un utilisateur
GET http://localhost:3000/api/checklists?utilisateurId=1
Content-Type: application/json




